---
- name: Kubernetees Cluster Setup
  hosts: Logstash-Nodes
  sudo: yes
  vars:
    ports: [6783/tcp, 30000-32767/tcp, 10250/tcp, 10255/tcp]
 
  tasks:
  - name: Opening Ports in Firewall
    firewalld:
      port: "{{ item }}"
      permanent: yes
      state: enabled
    with_items: "{{ports}}"

  - name: Reloading Firewall service
    service:
      name: firewalld
      state: reloaded

  - name: Disable SELinux
    selinux:
      state: disabled 

#  - name: creating directory
#    file:
#      path: /proc/sys/net/bridge
#      state: directory

#  - name: creating file
#    copy: 
#         content: "1" 
#         dest: "/proc/sys/net/bridge/bridge-nf-call-iptables"
#         backup: yes
#         owner: root
#         group: root
#         mode: 0755

  - name: creating kubernetes.repo file 
    file: 
       path: /etc/yum.repos.d/kubernetes.repo
       state: touch
       owner: root
       group: root
       mode: 0744

  - name: configuring Kubernetes Repostries on worker nodes
    blockinfile:
      path: /etc/yum.repos.d/kubernetes.repo
      block: |
        [kubernetes]
        name=Kubernetes
        baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
        enabled=1
        gpgcheck=1
        repo_gpgcheck=1
        gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg
                https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg

  - name: Installing Kubeadm
    yum:
      name:
        - kubeadm
      state: present
      update_cache: yes

  - name: adding repos for docker
    command: sudo subscription-manager repos --enable=rhel-7-server-rpms --enable=rhel-7-server-extras-rpms --enable=rhel-7-server-optional-rpms

  - name: Installing docker dependencies
    yum:
      name:
        - device-mapper-libs
        - device-mapper-event-libs 
      state: present
      update_cache: yes

  - name: Installing Docker
    yum:
      name:
        - docker
      state: present
      update_cache: yes

  - name: Restarting Docker and kublet
    shell: |
        systemctl enable docker
        systemctl restart docker
        systemctl enable kubelet
        systemctl restart kubelet
        swapoff -a

