# contains worker nodes of kubernetes 
# on these sah nodes Logstash containers will be bedeployed.
# while on R57 Linux Jump Host containerized services of Elasticsearch and Kibana will be deployed, and it will also be configured as a worker node

k8smaster:
  IP: 100.67.62.6
  user: root
  password: Dell0SS!

workernode1:
  IP: 100.67.60.59
  user: root
  password: Dell0SS!

workernode2:
  IP: 100.67.57.59
  user: root
  password: Dell0SS!

R57sahWorkerNode: 
  IP: 100.67.57.8
  user: root
  password: Dell0SS!

