---

- name: ELK stack
  hosts: LJH
  gather_facts: false
  tasks:
    - name: installed packages
      command: rpm -qa
      register: string
    - debug: var=string
    
    - name: Installing K8 Master
      shell: |
        setenforce 0
        sed -i --follow-symlinks 's/SELINUX=enforcing/SELINUX=disabled/g' /etc/sysconfig/selinux
      
